default_language_version:
  python: python3.12
default_stages: [ push ]
repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.5
    hooks:
      - id: ruff-check
      - id: ruff-format
        args: [ --check ]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-added-large-files
      - id: debug-statements
      - id: end-of-file-fixer
