site_name: HD Active
nav:
  - Notes: index.md
  - Development: development.md

theme:
  name: material
  logo: images/logo.png
  favicon: images/favicon.ico
  palette:
    primary: blue grey
    accent: indigo

markdown_extensions:
  - abbr
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji  # https://emojipedia.org/twitter/
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - tables

plugins:
  - search

repo_url: https://github.com/joaonc/hd_active
copyright: Copyright &copy; 2022 Joao Coelho
