name: Linting
# Linting tools use `pyproject.toml` for config.

on:
  - pull_request

jobs:
  linting:
    runs-on: ubuntu-latest
    env:
      UV_SYSTEM_PYTHON: '1'

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install requirements
        run: |
          uv pip install typer-invoke
          inv pip install requirements-dev

      - name: Lint and type check
        run: inv lint all --check
